### ISSUE TITLE
Error running test_pipeline_ingest_melbparkingdata.py 

### ISSUE THREAD

**Issue by osoroshi** [Azure-Samples/modern-data-warehouse-dataops#108] opened 2021-01-21 05:18 UTC
adf_pipeline_run = <function adf_pipeline_run.<locals>.make_adf_pipeline_run at 0x7fa837670ea0>
2021-01-21T03:24:52.5943351Z sql_connection = <pyodbc.Connection object at 0x7fa83631a390>
2021-01-21T03:24:52.5943875Z 
2021-01-21T03:24:52.5944497Z     def test_pipeline_succeeded(adf_pipeline_run, sql_connection):
2021-01-21T03:24:52.5945205Z         """Test that pipeline has data in SQL"""
2021-01-21T03:24:52.5946783Z >       this_run = adf_pipeline_run(PIPELINE_NAME, run_inputs={})
2021-01-21T03:24:52.5949547Z 
**2021-01-21T03:24:52.5950336Z tests/test_pipeline_ingest_melbparkingdata.py:10:** 

self = <azure.core.pipeline.policies._authentication.BearerTokenCredentialPolicy object at 0x7fa836310978>
request = <azure.core.pipeline.PipelineRequest object at 0x7fa8363170f0>

    def on_request(self, request):
        # type: (PipelineRequest) -> None
        """Adds a bearer token Authorization header to request and sends request to next policy.
    
        :param request: The pipeline request object
        :type request: ~azure.core.pipeline.PipelineRequest
        """
        self._enforce_https(request)
    
        if self._token is None or self._need_new_token:
>           self._token = self._credential.get_token(*self._scopes)
E           **AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'**

/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py:93: AttributeError

**Comment by ln-data-bass** [comment] 2021-02-23 22:20
any ideas on how to resolve this manually? I'm currently stuck on this bug.

cheers,

Lance

**Comment by ln-data-bass** [comment] 2021-02-23 22:28
I noticed this comment in the documentation "You may need to authorize the Pipelines initially to use the Service Connection for the first time." is this somehow related to the issue? How do I authorise the Pipelines to use the Service Connection?

**Comment by osoroshi** [comment] 2021-02-23 22:29
> any ideas on how to resolve this manually? I'm currently stuck on this bug.
> 
> cheers,
> 
> Lance

Not yet ut if you find a fix do let us know ;)

**Comment by ln-data-bass** [comment] 2021-02-24 04:12
> > any ideas on how to resolve this manually? I'm currently stuck on this bug.
> > cheers,
> > Lance
> 
> Not yet but if you find a fix do let us know ;)

as a workaround I added the parameter "continueOnError: true" to the file /devops/templates/jobs/integration-tests-job.yml

this at least allowed the whole pipeline to continue deploying to production instead of getting stuck at staging environment.

cheers,

Lance

**Comment by ln-data-bass** [comment] 2021-02-24 04:14
![image](https://user-images.githubusercontent.com/79294634/108946642-ebf6ac00-76b2-11eb-8873-d065f2b1f417.png)

**Comment by mdrakiburrahman** [comment] 2021-03-06 22:31
I ran into the same issue:
![image](https://user-images.githubusercontent.com/46581776/110222475-6d62f100-7ea0-11eb-92c4-c649885459b6.png)

The issue is actually not with this particular repo, but with [pytest-adf](https://pypi.org/project/pytest-adf/) from pypi. [pytest-adf](https://github.com/devlace/pytest-adf) is using `azure.common` for authenticating, which looks like it underwent a breaking change. The recommended path is to use `azure-identity` instead. [This Stackoverflow answer](https://stackoverflow.com/a/64087837/8954538) lead me to this.

To fix this:
1) I forked @devlace's `pytest-adf` repo into [pytest-adf-azure-identity](https://github.com/mdrakiburrahman/pytest-adf-azure-identity). Changed all the code that's using `azure.common` to use `azure-identity` instead
2) Published that version to pypi as [pytest-adf-azure-identity](https://pypi.org/project/pytest-adf-azure-identity/)
3) In the `requirements.txt` for the Integration Test, added the following:

![image](https://user-images.githubusercontent.com/46581776/110222589-4f49c080-7ea1-11eb-892a-4f0d77737b5e.png)

4) Integration tests works fine now:
![image](https://user-images.githubusercontent.com/46581776/110222612-7c966e80-7ea1-11eb-8718-4ef7680021fa.png)

![image](https://user-images.githubusercontent.com/46581776/110222619-8ae48a80-7ea1-11eb-9629-7a07e68998f0.png)

Once @devlace updates `pytest-adf` in PyPi to use `azure-identity`, this should be fixed.

**Comment by devlace** [comment] 2021-03-10 10:51
Thanks everyone for looking into this! `pytest-adf 0.1.4` is now updated to use `azure-identity`.

**Closed by devlace** 2021-03-10 10:51 UTC
Labels: bug, e2e: parking-sensors
